### ISSUE TITLE
Detect wrong encodings

### ISSUE THREAD

**Issue by utoPiC** [ico-apps/django-importer#14]
Non utf-8 uploaded files crashes the importers and don't gives errors. 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 218: invalid start byte`

Excel or Access in Windows usually produces ISO-8859-1 encoded csvs. We have to try to detect encoding or almost support common encodings. Can this task done at javascript level?

Discuss solution with @utoPiC

**Comment by cayop** [comment]
I think it is possible using more intensity the [Lib codecs](https://docs.python.org/3.6/library/codecs.html) 
In a bad case we can to do a try exception and support only UTF-8 and ISO-8859-1
The effort I think is about 8 hours

**Comment by slamora** [comment]
Fixed on PR #45
